In [1]:
# Importing libraries
import pandas as pd
import numpy as np

In [2]:
# Read csv file into a pandas dataframe
df = pd.read_csv("../raw/Earthquake_data.csv")

In [4]:
# Take a look at the first few rows
df.head()

,Year,Month,Day,Hour,Minute,Location,Latitude,Longitude,Magnitude,Deaths,Injuries,Damage in Millions,Damage Scale,Number of Houses Destroyed,Scale of houses destroyed,Number of Houses Damaged,Scale of houses damaged
0,2017,5,1,12.0,31.0,ALASKA: SKAGWAY; CANADA: BRITISH COLUMBIA,59.852,-136.677,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1988,11,25,23.0,46.0,"CANADA: QUEBEC: SAGUENAY, QUEBEC CITY",48.117,-71.183,5.8,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
2,2010,6,23,17.0,41.0,"CANADA: QUEBEC: VAL-DES-BOIS, GRACEFIELD",45.880,-75.480,5.2,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
3,2001,10,12,5.0,2.0,CANADA: QUEEN CHARLOTTE ISLANDS,52.630,-132.200,6.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2012,10,28,3.0,4.0,CANADA: QUEEN CHARLOTTE ISLANDS,52.788,-132.101,7.7,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0

In [5]:
# Total missing values for each feature i.e the columns
df.isnull().sum()

Year                             0
Month                            0
Day                              0
Hour                             1
Minute                           1
Location                         0
Latitude                         0
Longitude                        0
Magnitude                        0
Deaths                         133
Injuries                       138
Damage in Millions             133
Damage Scale                    30
Number of Houses Destroyed     176
Scale of houses destroyed      163
Number of Houses Damaged       177
Scale of houses  damaged       157
dtype: int64

In [6]:
# Total number of missing values
df.isnull().sum().sum()

1109

In [7]:
# Crreating a new dataframe to drop the uncessary columns which have alot of NaN values
new_df=df.iloc[:, 0:8]

In [8]:
new_df.head(50)

,Year,Month,Day,Hour,Minute,Location,Latitude,Longitude
0,2017,5,1,12.0,31.0,ALASKA: SKAGWAY; CANADA: BRITISH COLUMBIA,59.852,-136.677
1,1988,11,25,23.0,46.0,"CANADA: QUEBEC: SAGUENAY, QUEBEC CITY",48.117,-71.183
2,2010,6,23,17.0,41.0,"CANADA: QUEBEC: VAL-DES-BOIS, GRACEFIELD",45.880,-75.480
3,2001,10,12,5.0,2.0,CANADA: QUEEN CHARLOTTE ISLANDS,52.630,-132.200
4,2012,10,28,3.0,4.0,CANADA: QUEEN CHARLOTTE ISLANDS,52.788,-132.101
5,1970,6,24,13.0,9.0,"CANADA: QUEEN CHARLOTTE ISLANDS, BRITISH COLOMBIA",51.800,-131.000
6,2004,11,2,10.0,2.0,CANADA: VANCOUVER ISLAND,49.277,-128.772
7,1982,1,11,21.0,41.0,"CANADA; MAINE: CARIBOU, HAYNESVILLE, PRESQUE ISLE",46.975,-66.659
8,1968,9,25,10.0,38.0,MEXICO-GUATEMALA: S CHIAPAS,15.500,-92.700
9,1950,12,14,14.0,15.0,MEXICO: ACAPULCO,16.480,-98.220
10,1978,3,19,1.0,39.0,MEXICO: ACAPULCO,17.030,-99.740
11,2002,9,25,18.0,14.0,MEXICO: ACAPULCO,16.870,-100.113
12,1957,7,28,8.0,40.0,"MEXICO: ACAPULCO,MEXICO CITY",16.500,-99.100
13,2008,2,9,7.0,12.0,MEXICO: BAJA CALIFORNIA,32.456,-115.315
14,2010,4,4,22.0,40.0,MEXICO: BAJA CALIFORNIA,32.297,-115.278
15,1954,2,5,15.0,17.0,MEXICO: CHIAPAS,17.300,-92.600
16,1982,3,28,4.0,16.0,MEXICO: CHIAPAS,17.250,-93.210
17,2019,2,1,16.0,14.0,MEXICO: CHIAPAS; GUATEMALA: SAN MARCOS,14.763,-92.298
18,2015,12,17,19.0,49.0,MEXICO: COCOTITLAN,15.802,-93.633
19,1982,6,7,10.0,59.0,"MEXICO: GUERERRO, ORZIBA, OAXACA, GUADALUPE",16.558,-98.358
20,1950,11,17,19.0,28.0,MEXICO: GUERRERO,16.500,-100.400
21,1956,1,8,7.0,11.0,MEXICO: GUERRERO,17.000,-99.500
22,1964,7,6,7.0,22.0,MEXICO: GUERRERO,18.300,-100.400
23,1979,3,14,11.0,7.0,MEXICO: GUERRERO,17.813,-101.276
24,2011,12,11,1.0,47.0,MEXICO: GUERRERO,17.844,-99.963
25,2007,4,13,5.0,42.0,"MEXICO: GUERRERO, ATOYAC",17.302,-100.198
26,2004,1,1,23.0,31.0,"MEXICO: GUERRERO, MEXICO CITY",17.488,-101.303
27,2012,3,20,18.0,2.0,"MEXICO: GUERRERO, OAXACA",16.493,-98.231
28,1995,9,14,14.0,4.0,"MEXICO: GUERRERO, OAXACA, PUEBLA, MEXICO CITY",16.779,-98.597
29,1999,6,21,17.0,43.0,MEXICO: GUERRERO: COAHUAYUTLA; MICHOACAN: CUITZEO,18.324,-101.539
30,2014,4,18,14.0,28.0,MEXICO: GUERRERO; MEXICO CITY,17.397,-100.972
31,1959,8,26,8.0,25.0,MEXICO: GULF OF CAMPECHE,18.300,-94.400
32,1995,10,9,15.0,35.0,"MEXICO: JALISCO, MANZANILLO, SAN PATRICIO MELAQUE",19.055,-104.205
33,2009,12,30,18.0,48.0,MEXICO: MEXICALI,32.437,-115.165
34,2002,2,22,19.0,32.0,"MEXICO: MEXICALI, BAJA CALIFORNIA",32.319,-115.322
35,1976,6,7,14.0,26.0,MEXICO: MEXICO CITY,17.400,-100.640
36,1989,4,25,14.0,29.0,"MEXICO: MEXICO CITY, ACAPULCO",16.773,-99.328
37,1965,8,23,19.0,46.0,"MEXICO: ME\XICO CITY, OAXACA",16.300,-95.800
38,1997,1,11,20.0,28.0,"MEXICO: MICHOACAN, ARTEAGA",18.219,-102.756
39,1985,9,19,13.0,17.0,MEXICO: MICHOACAN: MEXICO CITY,18.190,-102.533
40,1981,10,25,3.0,22.0,MEXICO: MICHOACAN: LAZARO CARDENAS,18.048,-102.084
41,1980,6,9,3.0,28.0,MEXICO: NW,32.220,-114.985
42,1978,11,29,19.0,52.0,MEXICO: OAXACA,16.010,-96.591
43,1999,9,30,16.0,31.0,MEXICO: OAXACA,16.059,-96.931
44,2014,7,29,10.0,46.0,MEXICO: OAXACA,17.682,-95.653
45,2017,9,23,12.0,53.0,MEXICO: OAXACA,16.626,-95.078
46,2018,2,16,23.0,39.0,MEXICO: OAXACA,16.646,-97.653
47,1968,8,2,14.0,6.0,"MEXICO: OAXACA, GUERRERO",16.500,-97.800
48,1998,2,3,3.0,2.0,"MEXICO: OAXACA, SAN AGUSTIN, SAN FRANCISCO",15.883,-96.298
49,1983,1,24,8.0,17.0,MEXICO: OAXACA: SALINA CRUZ,16.147,-95.232

In [9]:
Earthquake_Data = new_df.to_csv("../Earthquake_data_cleaned.csv")